platform :ios, '13.2'
use_frameworks!

target 'Safeify' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end